"""
contentlab.publish.repo_export  --  Export a standalone, public per-article repo.

Bundles one post (`posts/<slug>/`) plus a vendored copy of the stdlib-only
`contentlab` package into a self-contained directory (`repos/<slug>/`), so the
article's "Code and data are open" link resolves to a clean repo that runs with
`python run.py` and no install step.

Layout produced (flattened to the repo root, see export_article docstring):

    <dest>/
      run.py config.py narrative.html excerpt.md   # the post, flattened
      data/        # cached AniList pull (optional)
      contentlab/  # vendored stdlib-only toolkit (so it runs with no deps)
      README.md LICENSE .gitignore

Public-repo rule: SOURCE + DATA only. Generated artifacts (`output/`) are NOT
shipped - they are reproducible via `python run.py` and are gitignored.

Stdlib only (shutil / pathlib).
"""
import shutil
from pathlib import Path

# never copy caches / cruft into the public repo
_IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store", ".env", ".env.*")

# files copied flat from the post dir to the repo root (skipped if absent)
_POST_FILES = ("run.py", "config.py", "narrative.html", "excerpt.md")

# output/ is generated by run.py and is never committed to a public article repo
_GITIGNORE = "__pycache__/\n*.pyc\n.DS_Store\n.env\n.env.*\noutput/\n"

_MIT = """MIT License

Copyright (c) {year} {holder}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


def _readme(*, title, summary, github_url, article_url, include_data):
    data_line = ("- `data/anime_raw.csv` - cached AniList pull, so the analysis is "
                 "reproducible offline.\n") if include_data else ""
    refresh = ("Uses the cached AniList pull in `data/`; pass `--refresh` to re-scrape."
               if include_data else "Pass `--refresh` to scrape AniList first.")
    article = f"\nPublished on the Haki Studios blog: {article_url}\n" if article_url else ""
    return f"""# {title}

The reproducible analysis behind the Haki Studios article **"{title}"**.
{article}
> {summary}

This repo is a frozen snapshot of the code and data that produced the article. It
runs on the Python 3 **standard library only** - no `pip install`.

## Run it

```bash
python run.py
```

{refresh} Outputs are written to `output/`:
- `post.html` - the full article body with the interactive charts inlined.
- `post_paste.html` - the same body with each chart wrapped in an `<iframe srcdoc>`.
- `results.json` + `yearly_stats.csv` - every number in the post, traceable.

## What's inside

- `run.py` - one entrypoint: load -> analyze -> build charts -> assemble.
- `config.py` - the knobs for this analysis (query, popularity floor, eras).
- `narrative.html` - the written post, with `{{{{CHART...}}}}` tokens for the charts.
{data_line}- `contentlab/` - vendored copy of the stdlib-only analysis + chart toolkit.

`output/` is created when you run it (the deliverables above) and is gitignored -
this repo ships source + data, not generated artifacts.

## Data

Scores are from the [AniList](https://anilist.co) GraphQL API (TV anime, Japan,
release years per `config.py`). "Score" is AniList's weighted `averageScore`. The
cached pull reflects list counts at scrape time.

## License

Code is MIT licensed (see `LICENSE`). Data is sourced from AniList under their terms.

A Haki Studios data-journalism project.
"""


def export_article(post_dir, contentlab_dir, dest, *, title, summary="",
                   github_url="", article_url=None, include_data=True,
                   holder="Haki Studios", year=2026, force=False):
    """Write a self-contained public repo for one post into `dest`.

    post_dir       : the post's source dir (posts/<slug>/)
    contentlab_dir : the toolkit package dir to vendor (contentlab/)
    dest           : target dir (repos/<slug>/); overwritten if force=True
    Returns the dest Path. Pure filesystem copy; does not touch git.
    """
    post_dir = Path(post_dir)
    contentlab_dir = Path(contentlab_dir)
    dest = Path(dest)

    if dest.exists():
        if not force:
            raise FileExistsError(f"{dest} already exists; pass force=True to overwrite")
        # clear the contents but PRESERVE the repo's own git history, so re-exports
        # update files in place and can be re-committed rather than losing the repo.
        for child in dest.iterdir():
            if child.name in (".git",):
                continue
            shutil.rmtree(child) if child.is_dir() else child.unlink()
    else:
        dest.mkdir(parents=True)

    # 1) the post, flattened to the repo root
    for name in _POST_FILES:
        src = post_dir / name
        if src.exists():
            shutil.copy2(src, dest / name)

    # 2) the cached data (the "data is open" promise). Generated output/ is NOT
    #    shipped - it is reproducible via run.py and is gitignored (public-repo rule).
    if include_data and (post_dir / "data").is_dir():
        shutil.copytree(post_dir / "data", dest / "data", ignore=_IGNORE)

    # 3) vendored toolkit so the repo runs with no install
    shutil.copytree(contentlab_dir, dest / "contentlab", ignore=_IGNORE)

    # 4) repo metadata
    (dest / "README.md").write_text(_readme(
        title=title, summary=summary, github_url=github_url,
        article_url=article_url, include_data=include_data), encoding="utf-8")
    (dest / "LICENSE").write_text(_MIT.format(year=year, holder=holder), encoding="utf-8")
    (dest / ".gitignore").write_text(_GITIGNORE, encoding="utf-8")

    return dest
